using System;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace Celeste.Tilemaps
{
    [System.Serializable]
    [CreateAssetMenu(fileName = "New Animated Tile", menuName = "Celeste/Tiles/Animated Tile")]
    public class AnimatedTile : TileBase
    {
        /// <summary>
        /// The List of Sprites set for the Animated Tile.
        /// This will be played in sequence.
        /// </summary>
        public Sprite[] m_AnimatedSprites;
        /// <summary>
        /// The minimum possible speed at which the Animation of the Tile will be played.
        /// A speed value will be randomly chosen between the minimum and maximum speed.
        /// </summary>
        public float m_Speed = 1f;
        /// <summary>
        /// The Collider Shape generated by the Tile.
        /// </summary>
        public Tile.ColliderType m_TileColliderType;

        private int currentFrame = 0;
        private float currentFrameTime = 0;
        private bool isPlaying = false;

        /// <summary>
        /// Retrieves any tile rendering data from the scripted tile.
        /// </summary>
        /// <param name="position">Position of the Tile on the Tilemap.</param>
        /// <param name="tilemap">The Tilemap the tile is present on.</param>
        /// <param name="tileData">Data to render the tile.</param>
        public override void GetTileData(Vector3Int position, ITilemap tilemap, ref TileData tileData)
        {
            tileData.transform = Matrix4x4.identity;
            tileData.color = Color.white;

            if (m_AnimatedSprites != null && m_AnimatedSprites.Length > 0)
            {
                tileData.sprite = m_AnimatedSprites[currentFrame];
                tileData.colliderType = m_TileColliderType;

                if (isPlaying)
                {
                    float timePerFrame = 1 / m_Speed;
                    currentFrameTime += Time.deltaTime;

                    while (currentFrameTime > timePerFrame && isPlaying)
                    {
                        currentFrameTime -= timePerFrame;
                        currentFrame = Math.Min(currentFrame + 1, m_AnimatedSprites.Length - 1);
                        isPlaying = currentFrame < m_AnimatedSprites.Length - 1;
                    }
                }
            }
        }

        public void PlayFromStart()
        {
            isPlaying = true;
            currentFrame = 0;
        }
    }
}